application: kepler-186f-11
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: django
  version: "latest"
- name: MySQLdb
  version: "latest"


builtins:
- django_wsgi: on


handlers:
- url: /static/admin
  static_dir: static/admin
  expiration: '0'

- url: /static
  static_dir: static

env_variables:
  DJANGO_SETTINGS_MODULE: 'ccrawler.settings'
